services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: expenseflow
      POSTGRES_PASSWORD: expenseflow
      POSTGRES_DB: expenseflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expenseflow -d expenseflow"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
